# For more information: https://laravel.com/docs/sail
version: '3.7'
services:
    gprd:
        build:            
            dockerfile: ./docker/Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8080}:8080'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            INVENTORY_ROAD_PATH: '${INVENTORY_ROAD_PATH}'
            SHAPE_PATH: '${SHAPE_PATH}'
            IMAGES_INVENTORY_ROAD_PATH: '${IMAGES_INVENTORY_ROAD_PATH}'
            LIBRARY_DOCUMENT_PATH: '${LIBRARY_DOCUMENT_PATH}'
            CLIMATIC_RISK_PATH: '${CLIMATIC_RISK_PATH}'
            DB_USERNAME: '${DB_USERNAME}'
            DB_PASSWORD: '${DB_PASSWORD}'
            DB_HOST: '${DB_HOST}'
            DB_PORT: '${DB_PORT}'            
        volumes:
            - './src:/var/www/html'
            - exclude_vendor:/var/www/html/vendor/
            - exclude_node:/var/www/html/node_modules/
        networks:
            - sail
        depends_on:
            - pgsql
            - redis

    pgsql:
        image: 'postgis/postgis:14-3.3'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_MULTIPLE_EXTENSIONS: 'postgis,hstore,postgis_topology,postgis_raster,pgrouting'
        volumes:
            - './sail-pgsql:/var/lib/postgresql/data'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s   

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - './sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
            
    pgadmin:
        image: dpage/pgadmin4
        volumes:
            - './backup:/var/lib/pgadmin4/storage'
        ports:
          - "5050:80" 
        depends_on:
          - pgsql 
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@hotmail.com
          PGADMIN_DEFAULT_PASSWORD: admin          
        networks:
          - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
    sail-redis:
        driver: local
volumes:
    exclude_vendor:
    exclude_node:
